version: "3"

networks:
  webnet:

volumes:
  db-data:

services:

  db:
    image: postgres:10.1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:


  adminer:
    image: adminer
    deploy:
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
    ports:
      - 8080:8080

  web:
    image: jdim/carservice
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

